### Declare base URL
@base_url = http://localhost:3001

### Welcome page
GET {{base_url}}/ HTTP/1.1

### Get all users
GET {{base_url}}/api/users HTTP/1.1

### Create a new user
POST {{base_url}}/api/users HTTP/1.1
Content-Type: application/json

{
  "user": {
    "email": "
    "password": "
    }
}
