### Declare base URL
@base_url = http://localhost:3001

### Welcome page
GET {{base_url}}/ HTTP/1.1

### Create a new user
POST {{base_url}}/api/users HTTP/1.1
Content-Type: application/json

{
    "name": "John Doe",
    "email": "jdoe@example.com",
    "password": "P@ssw0rd"
}

### Bad request - missing password
POST {{base_url}}/api/users HTTP/1.1
Content-Type: application/json

{
    "name": "John Doe",
    "email": "jdoe@example.com"
}

### Login a user
POST {{base_url}}/api/users/login HTTP/1.1
Content-Type: application/json

{
    "email": "jdoe@example.com",
    "password": "P@ssw0rd"
}

### Login with wrong email
POST {{base_url}}/api/users/login HTTP/1.1
Content-Type: application/json

{
    "email": "no-such-user@example.com",
    "password": "P@ssw0rd"
}

### Login with wrong password
POST {{base_url}}/api/users/login HTTP/1.1
Content-Type: application/json

{
    "email": "jdoe@example.com",
    "password": "NOT_REAL_PASSWORD"
}

@token = NOT_REAL_TOKEN

### Get user profile
GET {{base_url}}/api/users/me HTTP/1.1
Authorization: Bearer {{token}}

### Get user profile withouth token
GET {{base_url}}/api/users/me HTTP/1.1

### Get user profile with invalid token
GET {{base_url}}/api/users/me HTTP/1.1
Authorization: Bearer INVALID_TOKEN

