### Declare base URL
@base_url = http://localhost:3001
@token = NOT_REAL_TOKEN # Replace with the token you get from login
@ticket_id = NOT_REAL_TICKET_ID # Replace with the ticket id you get from creating a ticket

### Create a ticket (must be authenticated)
POST {{base_url}}/api/tickets HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "product": "AMD Ryzen 9 5950X",
    "description": "This is 1st ticket"
}

### Get all tickets (must be authenticated)
GET {{base_url}}/api/tickets HTTP/1.1
Authorization: Bearer {{token}}

### Get a specific ticket (must be authenticated)
GET {{base_url}}/api/tickets/{{ticket_id}} HTTP/1.1
Authorization: Bearer {{token}}

### Update a ticket (must be authenticated)
PUT {{base_url}}/api/tickets/{{ticket_id}} HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "product": "AMD Ryzen 9 5950X",
    "description": "This is 1st ticket",
    "status": "open"
}

### Create a note for a ticket (must be authenticated)
POST {{base_url}}/api/tickets/{{ticket_id}}/notes HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "text": "This is 1st note"
}

### Get all notes for a ticket (must be authenticated)
GET {{base_url}}/api/tickets/{{ticket_id}}/notes HTTP/1.1
Authorization: Bearer {{token}}

### Delete a ticket (must be authenticated)
DELETE {{base_url}}/api/tickets/{{ticket_id}} HTTP/1.1
Authorization: Bearer {{token}}
